site_name: rye-rp
theme: material

nav:
  - Home: index.md
  - python: python.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [python.rye_rp]
        options:
          show_source: false
