site_name: rypm
theme: material

nav:
  - Home: index.md
  - python: python.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [python.rypm]
        options:
          show_source: false
